apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: my-app-container
      image: nginx
      volumeMounts: 
      - name: config-volume
        mountPath: "/etc/config"
  volumes:
    - name: config-volume
      configMap:
        name: my-app-config

