apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-cronjob
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example
            image: busybox
            args:
            - /bin/sh
            - -c
            - "echo Running daily job!"
          restartPolicy: Never
