apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-job
spec:
  parallelism: 3
  completion: 6
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Hello from parallel job"]
      restartPolicy: Never

