apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  repllcas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: nginx
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
