apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example-replicaset
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["my-app"]
      - key: environment
        operator: In
        values: ["production", "staging"]
  template:
    metadata:
      labels:
        app: my-app
        environment: production
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80

